"""Add Alembic Version

Revision ID: ca2722a0e7a1
Revises: 
Create Date: 2024-08-06 11:40:59.923883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2722a0e7a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discipline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline',
    sa.Column('campus', sa.CHAR(length=9), nullable=False),
    sa.Column('discipline', sa.CHAR(length=38), nullable=False),
    sa.Column('department', sa.CHAR(length=24), nullable=False),
    sa.Column('schedule', sa.CHAR(length=6), nullable=False),
    sa.PrimaryKeyConstraint('campus', 'discipline', 'department', 'schedule')
    )
    # ### end Alembic commands ###
